version: "3"
services:
  app:
    image: nodefront
    container_name: nodefront
    build: ./
    restart: always
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
